# Generated by Django 2.1.2 on 2023-02-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='名字')),
                ('age', models.IntegerField(default=0, verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮件')),
            ],
            options={
                'verbose_name': '联系人',
                'verbose_name_plural': '联系人',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='joke01.Contact')),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_modules', models.TextField(verbose_name='用例模块')),
                ('case_description', models.TextField(verbose_name='用例描述')),
                ('case_precondition', models.TextField(verbose_name='前提条件')),
                ('operating_steps', models.TextField(verbose_name='操作步骤')),
                ('expected_result', models.TextField(verbose_name='预期结果')),
                ('test_result', models.TextField(verbose_name='测试结果')),
                ('remarks', models.TextField(blank=True, verbose_name='备注')),
                ('create_time', models.DateTimeField()),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
            },
        ),
    ]
